### ISSUE TITLE
Store detected Language per document during indexing

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/core-team#27]
> ⚠️: This issue is not an easy one, it requires some knowledge in Rust and more work than the other issues. 
I highly encourage beginners to take another issue.

## Summary

Meilisearch automatically detects the Script and the Language during indexing and search.
Because the searches only contain small texts, it is almost impossible to efficiently detect the used Language.
However, during indexing, Meilisearch receives complete documents on which it is easier to detect the Language, And so, instead of knowing the Language used in the search query, we could know the Language used in the data where we search in.

related to: https://github.com/meilisearch/product/discussions/532#discussioncomment-3709627

## technical approach
The first step

## Todo
- [ ] create a new database
  - [ ] implementation
- [ ] update this database during indexing
  - [ ] implementation
  - [ ] tests
- [ ] update this database during deletion
  - [ ] implementation
  - [ ] tests
